### PR TITLE
Update readme to reflect project status

### PR DESCRIPTION
**Pull request by gmaxwell**
Project is abandoned, unmaintained, and insecure.

### CODE REVIEW

**Comment by verretor** [comment]
Concept ACK.

**Comment by jfrader** [comment]
Ack

**Comment by donaloconnor** [comment]
Ack

**Comment by opetruzel** [comment]
ACK.

**Comment by rikur** [comment]
🥇

**Comment by kristapsk** [comment]
ACK

**Comment by patmillertime** [comment]
ACK

**Comment by zechendorf** [comment]
ACK

**Comment by PierreRochard** [comment]
utACK

**Pull request closed without merging**
