### PR TITLE
[consensus] Hard limit on transaction size / decouple from block size limit

### PR DESCRIPTION
**Pull request by jgarzik**
Establish a fixed upper limit on serialized transactions, compatible
    with existing software.
    
    Decouple transaction size limit from block size limit, by avoiding
    derivation of tx limit from block limit.

### CODE REVIEW

**Comment by afk11** [comment]
Where was the motivation for this change discussed? I've seen this proposed as a 'fix' for the transaction sighashing issue, but concerned as to why it's being introduced in this client. 

There are proposals that involve deleting private keys once time-locked transactions are pre-signed (specifically aimed at exchanges btw) https://blog.sldx.com/re-imagining-cold-storage-with-timelocks-1f293bfe421f

Here's a transaction which is over 100kb, evidence enough that if you add this, you're going to make bitcoins unspendable https://btc.com/42f4500dec4c6f8cd41337767bdf7e2caa48c153ae2114334a645ac927d03766

**Comment by afk11** [comment]
And another, more recent https://btc.com/15ccc1f7bd8ef8aa47821b63f42dd67faf2dded4ae1555fb8e9dcf97f5f72654

**Comment by afk11** [comment]
Scratch that, I miscounted a zero :/

**Comment by RCasatta** [comment]
We will need an hard-fork to have transaction greater than 1MB in the future? This fix apparently looks dictated by hurry. Isn't quadratic hashing solved by using midstate in segwit impl?

**Comment by jtimon** [comment]
Maybe the tests could be added to bitcoin core?

**Comment by jnewbery** [comment]
@jgarzik this is a change to consensus rules. Right now it's moot since the block size limit is 1MB, but if a 2MB hard fork does activate, then this is technically a soft fork from any clients which implement 2MB blocks but don't implement a 1MB tx size limit.

The usual way that consensus changes are proposed and agreed on is through the mailing list and BIP process. Can you point me to where the discussion for the SW/2MB HF proposal is?

The practical risk here is if a 2MB block HF is adopted by other clients, but they don't implement this 1MB tx soft fork, then users of the btc1 client would fall out of consensus with the rest of the network if there's a block containing a tx > 1MB.

**Comment by JaredR26** [comment]
>  This fix apparently looks dictated by hurry. Isn't quadratic hashing solved by using midstate in segwit impl?

Segwit doesn't require that clients use segwit.  This same concept could allow covert asicboost to continue operating if not blocked as part of the hardfork.

**Comment by jgarzik** [comment]
For reference: https://github.com/btc1/specifications/blob/master/drafts/BIP-tx-size.md

**Comment by mbelshe** [comment]
Sorry for the late review; overall looks good.

Small nit - There is a reference to MAX_BLOCK_BASE_SIZE in bitcoin-tx.cpp utility which should probably now use MAX_TX_BASE_SIZE.  See function MutateAddTxInput().

**Pull request merged**
