### PR TITLE
Add explanation & Gox Coin Retrieval

### PR DESCRIPTION
**Pull request by BitcoinErrorLog**
I have updated the readme.md to include a brief summary of this fork, as well as details about the recent order of Judge Jiminy Cricket to undo the Goxing in the first Bitcon fork to happen. Centralize all the things!

### CODE REVIEW

**Comment by hoffmabc** [comment]
Funny, doing your best Vitalik impression. NACK.

**Comment by BitcoinErrorLog** [comment]
I'm new to this whole programming thing. Is syntax important?!

**Comment by BenedictThompson-zz** [comment]
NACK. We are not ethereum.

**Comment by Buck-Rogers** [comment]
Do not send the gox coins to silbert, we should send the funds as a "anyone can spend", you know they will get to the right place then :-).

**Review by jli225 — COMMENTED** [review]
Sad to see that you have been brainwashed by BSCore. Don't worry, the whole Bitcoin community will no longer show indifference. If you want a Core Committee-controlled, cencorship-directed Bitcoin, 
 +this is NOT the fork for you!
Core Committee was no longer decentralized after Vladimir colluded with Blockstream to hijack the Core from Satoshi and gavin by spending millions per month.
Permanent monopoly in development is NOT accept, because this is Bitcoin. Leader-less.
Bitcoin is here to stay, with or without current Core Committee.

**Pull request closed without merging**
