### PR TITLE
Hardcoded seeds

### PR DESCRIPTION
**Pull request by kleetus**
* Changed hardcoded seeds to records supporting segwit2x

### CODE REVIEW

**Comment by christophebiocca** [comment]
Issues that may need to be resolved (either before landing or before shipping):

- `seed.bloq.com` and `seed.blockchain.info` don't yet return any `A` records, probably because they haven't been setup yet?
- `seed.mainnet.b-pay.net` and `seed.ob1.io` only return one entry. This might be for a variety of reasons, but serving multiple nodes at once is probably better.
- The entry from `seed.mainnet.b-pay.net` and `seed.ob1.io` doesn't seem to rotate (although that might just be because of sampling-interval issues on my end, or because there's not a whole lot of segwit2x nodes on mainnet). Not rotating -> lots of peers will end up connected to just that one node.

**Comment by cpacia** [comment]
I'm working on seed.ob1.io

**Comment by kleetus** [comment]
> seed.bloq.com and seed.blockchain.info don't yet return any A records, probably because they haven't been setup yet?

Correct

> seed.mainnet.b-pay.net and seed.ob1.io only return one entry. This might be for a variety of reasons, but serving multiple nodes at once is probably better.

The intention is to use sipa's code for dynamic discovery for the b-pay node. I need to write the glue code to update the A record.  But, I don't think that will/should be a prereq for this merge request? 

> The entry from seed.mainnet.b-pay.net and seed.ob1.io doesn't seem to rotate (although that might just be because of sampling-interval issues on my end, or because there's not a whole lot of segwit2x nodes on mainnet). Not rotating -> lots of peers will end up connected to just that one node.

This speaks to the fact that all hardcoded seeds should use dynamically discovered hosts.

**Comment by christophebiocca** [comment]
>  I don't think that will/should be a prereq for this merge request?

Not really, it can proceed in parallel. The lack of rotation/low returned node count only will start having a real impact once/if SPV wallets start pointing to the new seeds nodes, because they exclusively rely on the DNS seeds.

**Comment by kleetus** [comment]
As far as dynamic discovery, by not using service bits, it will be difficult to know for sure if the results from a dns query will yield segwit2x nodes. It would be best to offer at least 1 guaranteed segwit2x-enabled full node. So, for now, I won't dynamically populate. I'll watch user-agents and proceed from there.

**Comment by jheathco** [comment]
Do we want another seed or are these adequate?  I can set one up on the btcfaucet server I had configured and get a proper CNAME for it.  Noticed the commit dropped the server count from 6 to 5.

**Comment by afk11** [comment]
Why are no existing seeds left after this change?

**Comment by petertodd** [comment]
> Why are no existing seeds left after this change?

Indeed, the way seeds - and Bitcoin's security model - works is that having additional sources of blockchain data add to your security, by making it harder for the attacker to control all sources of blockchain data. Even if a seed is outright malicious it can't harm you any more than not having the seed at all.

It's also irresponsible to flag-day transition to an entirely new set of untested infrastructure, run by entities inexperienced in running DNS seeds, rather than a gradual approach.

**Comment by petertodd** [comment]
Also, as Adam Back [pointed out](https://twitter.com/adam3us/status/885790767637307392) other than ob1, every seed will be members of blockchain alliance (pre-emptive KYC customer info sharing with law enforcement) bloq/Skry & blockchain. Obviously, this raises privacy and censorship resistance questions.

**Comment by afk11** [comment]
@petertodd Quite right. 

"It would be best to offer at least 1 guaranteed segwit2x-enabled full node. So, for now, I won't dynamically populate. I'll watch user-agents and proceed from there."

@kleetus Are user-agents enough to guarantee the node runs 2x? I'd imagine the only sure way to do this is to send people to nodes you yourself control, which might bolster some of Peters concerns.

Given that none of the other DNS seeds implement filtering of node-versions, they too will end up advertising segwit2x nodes, which alleviates some of the privacy concerns. Removing the other seeds makes this change harmful, especially since 3 of the 4 seeds in this PR are located in a single country.

**Review by PaulSnow — CHANGES_REQUESTED** [review]
Should have more seeds, not fewer.

**Comment by jgarzik** [comment]
Anyone who wants to run a seed that finds and returns 2x nodes is welcome.

The goal is to avoid overwhelming nodes with garbage, if they have an empty address manager.  If that is the case, then the node will waste a lot of time before finding a useful node.

**Comment by jgarzik** [comment]
Superceded by #74 - taking this feedback into account - new change just adds seeds.

**Pull request closed without merging**
