### PR TITLE
Implement BIP91 Reduced threshold Segwit MASF

### PR DESCRIPTION
**Pull request by jameshilliard**
This is an implementation of BIP91.
BIP91 details: https://github.com/bitcoin/bips/blob/master/bip-0091.mediawiki
Previous discussion:
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2017-May/014380.html

### CODE REVIEW

**Comment by petertodd** [comment]
Concept ACK

**Comment by bgorlick** [comment]
Concept ACK

**Comment by Leviathn** [comment]
Tested ACK.

**Comment by tmornini** [comment]
Very clean and simple. 👍🏻

**Comment by jgarzik** [comment]
Thanks!   Definitely a useful starting point and is aligned with the segwit2x agreement.

**Comment by deadalnix** [comment]
There are no unit tests.

**Comment by jgarzik** [comment]
Incorporated and superceded

**Comment by hsjoberg** [comment]
Concept ACK

**Pull request closed without merging**
