### PR TITLE
Only hardfork if Segwit2x actually activates

### PR DESCRIPTION
**Pull request by luke-jr**
If Segwit is activated without Segwit2x, it isn't appropriate to hardfork.

### CODE REVIEW

**Comment by hoffmabc** [comment]
What a beautiful fuck you victory lap submission before August 1st. I commend your dedication Luke-jr.

**Comment by JaredR26** [comment]
Trolling really is Luke's most impressive skill.

**Comment by jgarzik** [comment]
@hoffmabc @JaredR26 Let's keep it professional please.

@luke-jr Thanks for the change.  This is outside the scope of segwit2x group, which assumes bit-4 Segwit && HF.  If SegWit is purely Bit-1 then it won't trigger.

**Comment by luke-jr** [comment]
@jgarzik The current code triggers the hardfork if purely-bit-1 Segwit activates. This fixes that so it only triggers via bit-4.

**Comment by kek-coin** [comment]
@jgarzik 

> If SegWit is purely Bit-1 then it won't trigger.

Could you point me to the code where this is enforced? Afaict @luke-jr aimed to achieve precisely that; I've skimmed the diff between BTC1 and the 0.14 branch of bitcoin/bitcoin and saw no check for this. In fact, it superficially seems that [BIP102active == fSegwitSeasoned](https://github.com/btc1/bitcoin/blob/40b98d9d04630194f7b9d78fd534eb22445ff663/src/consensus/consensus.h#L15).

**Comment by jgarzik** [comment]
Since this is now the subject of false claims on social media, let's be hyper-specific on this issue.

Approx. 30 days ago - this PR was filed 13 days ago - I noted that the HF logic was [SegWit activation + 3 months](https://www.reddit.com/r/btc/comments/6i16gl/psa_how_segwit2x_actually_works/dj2qdaz/?utm_content=permalink&utm_medium=user&utm_source=reddit&utm_name=frontpage).

The most likely path - NYA agreement hashpower following through on their promised path - is now taking place as of this writing.  bit-4 will activate bit-1 will activate SegWit will activate the HF.   The most likely scenario is that hashpower and NYA agreement will continue as expected, and hashpower will enforce 2M HF as expected.

This suggested change is therefore not required but is a "nice to have."

Section 4b of the [release notes](https://lists.linuxfoundation.org/pipermail/bitcoin-segwit2x/2017-July/000147.html) of segwit2x v1.14.4 offer, in an effort to take feedback and gain wider consensus, to re-consider merging something like luke-jr's suggested PR here.

**Comment by howtoaddict** [comment]
@jgarzik thank you for staying above childish nonsense that has been going on lately. And thanks @luke-jr for pull request.

**Comment by jheathco** [comment]
If the signatories for NYA follow though with their commitments to deploy segwit2x, this should be a non-issue.  In the case that some participants do not, and segwit activates without a significant majority signaling on bit-4, it seems that this would prevent a potentially contentious hard fork - I'd tend to agree with @luke-jr on this one.

**Comment by jheathco** [comment]
Looks like this can issue can be closed given the fact that 80%+ are currently signaling on bit4 - pretty obvious at this point segwit2x/BIP91 will be responsible for activating segwit.

**Comment by jgarzik** [comment]
Events rendered moot.

**Pull request closed without merging**
